### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by headbanger777** [kriswebdev/cryptsetup-deluks#5]
@kriswebdev 
Thanks for this great work , and great idea
i tried sooooooo many times , on ubuntu 16.04 and Mint 18 ( i guess both are xenial xerus and they should be ok with grub crypto deluks and cryptsetup-deluks )

with real machine , and inside Vitual Machine
i read and followed the guides step by step
but it's not working. 
When i press "c" at grub prompt , and type the command "cryptomout -x /"
i receive the message "SLOT 0 opened"
but when i check with command "ls"
there is only (crypto0) 
But there is not any (crypto0,msdos2) or (crypto0,msdos1)
and so other commands like "set boot (crypto0,msdosX) and .... are not working 

can some one please help me.

**Comment by kriswebdev** [comment]
Just tested, confirmed to not work  using Ubuntu 16.04.3 (Virtualbox env.).
Cryptsetup reads the encrypted disk, GRUB cryptomount opens it but doesn't find the partitions.
Checking why.

**Comment by kriswebdev** [comment]
OK so the issue lies in grub-cryptomount-deluks last commit.

Until it's fixed, her's the workaround:

Go back in `grub-crypto-deluks` folder of decoy OS, run:

```
rm -rf grub-crypto-deluks
git clone --depth 2 https://github.com/kriswebdev/grub-crypto-deluks.git
cd grub-crypto-deluks
git checkout 8b2e38b
make clean
./linguas.sh
./autogen.sh
./configure --prefix=/usr --exec_prefix=/usr --sysconfdir=/etc 
make
sudo make install
sudo grub-install /dev/sdX
```

**Comment by headbanger777** [comment]
Thank you very much for replying.
I tried with **1 hdd , in a real machine**
and with **2 hdd , inside Virtual box** , and also i tested **2 hdd inside  VMWare workstation 14**
both ubuntu 
i tried with both of these .iso :   ubuntu-16.04.3-desktop-amd64.iso   &   linuxmint-18.3-xfce-64bit.iso
i guess my kernel version is:  4.10.0-28

The only error i experienced during installation is when i'm installing Grub-Crypto-Deluks
the command: "make clean" 
shows error ,  make: *** no rule to make target 'clean'

**Comment by kriswebdev** [comment]
OK, last grub-cryptomount-deluks commit reverted.
That will fix it without the workaround.
